const languagekey = {
  en: {
    SIGN_UP: "SIGN UP",
    LOGIN: "LOGIN",
    WIARA_SERVER: "WIARA SERVER",
    LOGIN_WELCOME_BACK: "Welcome Back",
    LOGIN_WELCOME_DEC: "Please login to your account by filling this form ...",
    LOGIN_ENTER_USERNAME: "Enter username ...",
    LOGIN_ENTER_PASSWORD: "Enter password ...",
    LOGIN_REMEMBER_ME: "Remember me",
    LOGIN_FORGET_PASSWORD: "Forget password !",
    LOGIN_ERROR_USERNAME: "Please enter email or username",
    LOGIN_ERROR_PASSWORD: "Please enter password",
    LOGIN_ERROR_INFO: "The information entered is incorrect",
    REGISTER_PERSONAL_INFO: "Personal Information",
    REGISTER_CONTACT: "Contact",
    REGISTER_ACCOUNT: "Account",
    REGISTER_HAVE_ACCOUNT: "Already have an account?",
    REGISTER_SIGN_IN: " Sign In",
    REGISTER_CREATE_ACCOUNT: "Create your account",
    REGISTER_CREATE_DEC: "You must create your account to login first ...",
    REGISTER_ENTER_NAME: "Enter your first name ....",
    REGISTER_ENTER_LASTNAME: "Enter your lastname ...",
    REGISTER_ENTER_AGE: "Enter your age ...",
    REGISTER_MALE: "Male",
    REGISTER_FEMALE: "Female",
    REGISTER_NEXT_STEP: "NEXT STEP",
    REGISTER_PREVIOUS_STEP: "PREV STEP",
    REGISTER_ACCOUNT_LETS_GO: "Let's Go",
    REGISTER_FOR_EXAMPLE_ALIREZA: "For example 'Alireza'",
    REGISTER_FOR_EXAMPLE_AKBARI: "For example 'Akbari'",
    REGISTER_FOR_EXAMPLE_AGE: "For example '18'",
    REGISTER_CONTACT_INFO: "Contact information",
    REGISTER_CONTACT_DEC: "Please enter your email and mobile number ...",
    REGISTER_ENTER_EMAIL: "Enter your email ...",
    REGISTER_ENTER_PHONE_NUMBER: "Enter your mobile number ...",
    REGISTER_SEND_TO_EMAIL: "Send notifications to email",
    REGISTER_SEND_TO_PHONE_NUMBER: "Send notifications to mobile number",
    REGISTER_VALIDATION: "VALIDATION",
    REGISTER_FOR_EXAMPLE_EMAIL: "For example 'example@gmail.com'",
    REGISTER_FOR_EXAMPLE_PHONE_NUMBER: "For example '09151234567'",
    REGISTER_VALIDATION: "Validation",
    REGISTER_VALIDATION_DEC:
      "Enter the codes sent to your email and mobile number ...",
    REGISTER_VALIDATION_EMAIL: "Enter the code sent for the email ...",
    REGISTER_VALIDATION_NUMBER: "Enter the code sent for the mobile ...",
    REGISTER_VALIDATION_CODE_EXPIRATION: "Code expiration in ",
    REGISTER_VALIDATION_DONT_RECEIVE: "Dont receive the Code? ",
    REGISTER_VALIDATION_RESEND: "Resend Code",
    REGISTER_VALIDATION_FOR_EXAMPLE_EMAIL: "For example 'A5S7R8'",
    REGISTER_VALIDATION_FOR_EXAMPLE_NUMBER: "For example 'C3B3GT'",
    REGISTER_ACCOUNT_INFO_OOC: "Account information - ooc",
    REGISTER_ACCOUNT_INFO_OOC_DEC:
      "Enter the required information to login to your account ...",
    REGISTER_ACCOUNT_INFO_OOC_USERNAME: "Enter username ...",
    REGISTER_ACCOUNT_INFO_OOC_USERPASSWORD: "Enter password ...",
    REGISTER_ACCOUNT_INFO_OOC_RE_USERPASSWORD: "Enter confirm password ...",
    REGISTER_ACCOUNT_INFO_OOC_UNIC_USERNAME:
      "Your username is used for the RPG server username",

    REGISTER_ACCOUNT_INFO_IC: "Account information - ic",
    REGISTER_ACCOUNT_INFO_IC_DEC: "Select the mode you want ...",
    REGISTER_ACCOUNT_INFO_IC_RP_RPG_TEXT: "CHARACTER INFORMATION",
    REGISTER_ACCOUNT_INFO_IC_RP_NAME: "Enter your Ic Name ...",
    REGISTER_ACCOUNT_INFO_IC_RP_LASTNAME: "Enter your Ic Lastname ...",
    REGISTER_ACCOUNT_INFO_IC_RP_DATE_OF_BIRTH:
      "Enter your Ic Date of birth ...",
    REGISTER_ACCOUNT_INFO_IC_RP_FOR_EXAMPLE_NAME: "For example 'Carl'",
    REGISTER_ACCOUNT_INFO_IC_RP_FOR_EXAMPLE_LASTNAME: "For example 'Jackson'",
    REGISTER_ACCOUNT_INFO_IC_RP_FOR_EXAMPLE_DATE_OF_BIRTH:
      "For example '05/06/2022'",
  },
  fa: {
    SIGN_UP: "ثبت نام",
    LOGIN: "ورود",
    WIARA_SERVER: "سرور ویارا",
    LOGIN_WELCOME_BACK: "خوش آمدید",
    LOGIN_WELCOME_DEC: "لطفا با پر کردن این فرم وارد حساب کاربری خود شوید ...",
    LOGIN_ENTER_USERNAME: "نام کاربری خود را وارد کنید ...",
    LOGIN_ENTER_PASSWORD: "رمز عبور را وارد کنید ...",
    LOGIN_REMEMBER_ME: "من را به خاطر بسپار",
    LOGIN_FORGET_PASSWORD: "فراموشی رمز عبور !",
    LOGIN_ERROR_USERNAME: "لطفا نام کاربری و یا ایمیل خود را وارد کنید",
    LOGIN_ERROR_PASSWORD: "لطفا رمز عبور خود را وارد کنید",
    LOGIN_ERROR_INFO: "اطلاعات وارد شده اشتباه است",
    REGISTER_PERSONAL_INFO: "اطلاعات شخصی",
    REGISTER_CONTACT: "تماس",
    REGISTER_ACCOUNT: "حساب",
    REGISTER_HAVE_ACCOUNT: "از قبل حساب کاربری دارید؟",
    REGISTER_SIGN_IN: " ورود کنید",
    REGISTER_CREATE_ACCOUNT: "حساب کاربری خود را بسازید",
    REGISTER_CREATE_DEC:
      "ابتدا باید حساب کاربری خود را ایجاد کنید تا وارد شوید ...",
    REGISTER_ENTER_NAME: "نام خود را وارد کنید ...",
    REGISTER_ENTER_LASTNAME: "فامیل خود را وارد کنید ...",
    REGISTER_ENTER_AGE: "سن خود را وارد کنید ...",
    REGISTER_MALE: "مرد",
    REGISTER_FEMALE: "زن",
    REGISTER_NEXT_STEP: "مرحله بعدی",
    REGISTER_PREVIOUS_STEP: "مرحله قبلی",
    REGISTER_ACCOUNT_LETS_GO: "بزن بریم",
    REGISTER_FOR_EXAMPLE_ALIREZA: "به عنوان مثال: علیرضا",
    REGISTER_FOR_EXAMPLE_AKBARI: "به عنوان مثال: اکبری",
    REGISTER_FOR_EXAMPLE_AGE: "به عنوان مثال: 18",
    REGISTER_CONTACT_INFO: "اطلاعات تماس",
    REGISTER_CONTACT_DEC: "لطفا ایمیل و شماره موبایل خود را وارد کنید ...",
    REGISTER_ENTER_EMAIL: "ایمیل خود را وارد کنید ...",
    REGISTER_ENTER_PHONE_NUMBER: "شماره موبایل خود را وارد کنید ...",
    REGISTER_SEND_TO_EMAIL: "ارسال اعلان ها به ایمیل",
    REGISTER_SEND_TO_PHONE_NUMBER: "ارسال اعلان ها به شماره موبایل",
    REGISTER_VALIDATION: "اعتبار سنجی",
    REGISTER_FOR_EXAMPLE_EMAIL: "به عنوان مثال: example@gmail.com",
    REGISTER_FOR_EXAMPLE_PHONE_NUMBER: "به عنوان مثال: 09151234567",
    REGISTER_VALIDATION: "اعتبار سنجی",
    REGISTER_VALIDATION_DEC:
      "کدهای ارسالی به ایمیل و شماره موبایل خود را وارد کنید ...",
    REGISTER_VALIDATION_EMAIL: "کد ارسالی به ایمیل را وارد کنید ...",
    REGISTER_VALIDATION_NUMBER: "کد ارسالی به شماره موبایل را وارد کنید ...",
    REGISTER_VALIDATION_CODE_EXPIRATION: "انقضا کد در ",
    REGISTER_VALIDATION_DONT_RECEIVE: "کد را دریافت نکردید؟ ",
    REGISTER_VALIDATION_RESEND: "ارسال مجدد کد",
    REGISTER_VALIDATION_FOR_EXAMPLE_EMAIL: "به عنوان مثال: 'A5S7R8'",
    REGISTER_VALIDATION_FOR_EXAMPLE_NUMBER: "به عنوان مثال: 'C3B3GT'",
    REGISTER_ACCOUNT_INFO_OOC: "اطلاعات اکانت - ooc",
    REGISTER_ACCOUNT_INFO_OOC_DEC:
      "اطلاعات درخواست شده را برای ورود وارد کنید ...",
    REGISTER_ACCOUNT_INFO_OOC_USERNAME: "نام کاربری را وارد کنید ...",
    REGISTER_ACCOUNT_INFO_OOC_USERPASSWORD: "رمز عبور را وارد کنید ...",
    REGISTER_ACCOUNT_INFO_OOC_RE_USERPASSWORD:
      "تکرار رمز عبور را وارد کنید ...",
    REGISTER_ACCOUNT_INFO_OOC_UNIC_USERNAME:
      "نام کاربری شما با نام کاربری سرور RPG برابر است",

    REGISTER_ACCOUNT_INFO_IC: "اطلاعات اکانت - ic",
    REGISTER_ACCOUNT_INFO_IC_DEC: "حالت مورد نظر را انتخاب کنید ...",
    REGISTER_ACCOUNT_INFO_IC_RP_RPG_TEXT: "اطلاعات شخصیت",
    REGISTER_ACCOUNT_INFO_IC_RP_NAME: "نام IC را وارد کنید ...",
    REGISTER_ACCOUNT_INFO_IC_RP_LASTNAME: "نام خانوادگی IC را وارد کنید ...",
    REGISTER_ACCOUNT_INFO_IC_RP_DATE_OF_BIRTH:
      "تاریخ تولد IC را وارد کنید ...",
    REGISTER_ACCOUNT_INFO_IC_RP_FOR_EXAMPLE_NAME: "برای مثال: Carl",
    REGISTER_ACCOUNT_INFO_IC_RP_FOR_EXAMPLE_LASTNAME: "برای مثال: Jackson",
    REGISTER_ACCOUNT_INFO_IC_RP_FOR_EXAMPLE_DATE_OF_BIRTH:
      "برای مثال: 05/06/2022",
  },
};
