import "./event";
import "./keyup";
import "./keyDown";
import "./everyTick";
import "./vehicle";
import "./blips";
import "./mapclick";
import "./manageStaticBlips";
import "./peds";
import "./manageStaticNPCs";
import "./manageEyeTrackerFounded";
import "./AFK";
//edit kon
import './load3DText'
import "./functions";
