export const clothesShops = {
  198145: {
    ClothesInteriorID: 198145,
    ClothesID: 1,
    Suggestions: {
      1: {
        male: [
          { componentID: 3, drawableID: 1, textureID: 0 },
          { componentID: 4, drawableID: 10, textureID: 0 },
          { componentID: 6, drawableID: 97, textureID: 0 },
          { componentID: 8, drawableID: 3, textureID: 0 },
          { componentID: 11, drawableID: 4, textureID: 0 },
        ],
        female: [],
      },
    },
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [
        {
          ComponentID: 4,
          ComponentName: "Legs",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 0,
            },
            {
              nameInInvoice: "Shalvarak shatranji",
              DrawableID: 2,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar parcheyi",
              DrawableID: 10,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar Jib Dar",
              DrawableID: 9,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvarak",
              DrawableID: 12,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar parcheii",
              DrawableID: 13,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvarak",
              DrawableID: 16,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar tarh dar",
              DrawableID: 26,
              isNeedTorsos: false,
              Price: 1,
            },
          ],
        },
      ],
      female: [],
    },
    ClothProp: {
      male: [
        {
          PropID: 0,
          PropName: "Hats",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 8,
              isNeedTorsos: false,
              Price: 0,
            },
            {
              nameInInvoice: "test1",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "test1",
              DrawableID: 2,
              isNeedTorsos: false,
              Price: 1,
            },
          ],
        },
      ],
      female: [],
    },
  },
  171265: {
    ClothesInteriorID: 171265,
    ClothesID: 2,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [
        {
          ComponentID: 4,
          ComponentName: "Legs",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 0,
            },
            {
              nameInInvoice: "Pizame",
              DrawableID: 29,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar band dar",
              DrawableID: 30,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar jib dar",
              DrawableID: 31,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar s-lash",
              DrawableID: 33,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar jib dar",
              DrawableID: 34,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar kar",
              DrawableID: 36,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar band dar",
              DrawableID: 41,
              isNeedTorsos: false,
              Price: 1,
            },
          ],
        },
      ],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  169217: {
    ClothesInteriorID: 169217,
    ClothesID: 3,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [
        {
          ComponentID: 4,
          ComponentName: "Legs",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 0,
            },
          ],
        },
      ],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  137217: {
    ClothesInteriorID: 137217,
    ClothesID: 4,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [
        {
          ComponentID: 4,
          ComponentName: "Legs",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 0,
            },
            {
              nameInInvoice: "Shalvar 4jib",
              DrawableID: 46,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar arteshi",
              DrawableID: 51,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar arteshi",
              DrawableID: 53,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar lash",
              DrawableID: 59,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvarak boland",
              DrawableID: 62,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Pizame",
              DrawableID: 65,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar tarh dar",
              DrawableID: 68,
              isNeedTorsos: false,
              Price: 1,
            },
          ],
        },
      ],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  166145: {
    ClothesInteriorID: 166145,
    ClothesID: 5,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [
        {
          ComponentID: 4,
          ComponentName: "Legs",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 0,
            },
          ],
        },
      ],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  165633: {
    ClothesInteriorID: 165633,
    ClothesID: 6,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [
        {
          ComponentID: 4,
          ComponentName: "Legs",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 0,
            },
          ],
        },
      ],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  235265: {
    ClothesInteriorID: 235265,
    ClothesID: 7,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [
        {
          ComponentID: 4,
          ComponentName: "Legs",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 0,
            },
          ],
        },
      ],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  140801: {
    ClothesInteriorID: 140801,
    ClothesID: 8,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [
        {
          ComponentID: 4,
          ComponentName: "Legs",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 0,
            },
          ],
        },
      ],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  176129: {
    ClothesInteriorID: 176129,
    ClothesID: 9,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [
        {
          ComponentID: 4,
          ComponentName: "Legs",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 0,
            },
          ],
        },
      ],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  175361: {
    ClothesInteriorID: 175361,
    ClothesID: 10,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [
        {
          ComponentID: 4,
          ComponentName: "Legs",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 0,
            },
            {
              nameInInvoice: "Shalvar tarh dar",
              DrawableID: 69,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar tarh dar",
              DrawableID: 70,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar tarhe dokht",
              DrawableID: 73,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar tarhe dokht kotah",
              DrawableID: 74,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar tarhe dokht",
              DrawableID: 75,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar zap dar",
              DrawableID: 76,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar hockey",
              DrawableID: 84,
              isNeedTorsos: false,
              Price: 1,
            },
          ],
        },
      ],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  202497: {
    ClothesInteriorID: 202497,
    ClothesID: 11,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [
        {
          ComponentID: 4,
          ComponentName: "Legs",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 0,
            },
            {
              nameInInvoice: "Shalvar lole tofangi tarh dar",
              DrawableID: 85,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar arteshi",
              DrawableID: 86,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar arteshi pache kotah",
              DrawableID: 87,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shavarak arteshi",
              DrawableID: 88,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shavarak arteshi",
              DrawableID: 89,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Salvar fagh boland",
              DrawableID: 90,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar band dar",
              DrawableID: 92,
              isNeedTorsos: false,
              Price: 1,
            },
          ],
        },
      ],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  183553: {
    ClothesInteriorID: 183553,
    ClothesID: 12,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [
        {
          ComponentID: 4,
          ComponentName: "Legs",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 0,
            },
            {
              nameInInvoice: "Shalvar 2rang kotah",
              DrawableID: 97,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar 2rang",
              DrawableID: 98,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar shekar",
              DrawableID: 107,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar daste do",
              DrawableID: 111,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar khaz",
              DrawableID: 112,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar jib dar",
              DrawableID: 122,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar jib dar kotah",
              DrawableID: 123,
              isNeedTorsos: false,
              Price: 1,
            },
          ],
        },
      ],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  179713: {
    ClothesInteriorID: 179713,
    ClothesID: 13,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [
        {
          ComponentID: 4,
          ComponentName: "Legs",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 0,
            },
            {
              nameInInvoice: "Shalvar arteshi",
              DrawableID: 133,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar sade",
              DrawableID: 134,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar sade",
              DrawableID: 143,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar tarh dar",
              DrawableID: 142,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar tarh dar",
              DrawableID: 140,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar tarh dar",
              DrawableID: 139,
              isNeedTorsos: false,
              Price: 1,
            },
          ],
        },
      ],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
};
