export const clothesShops = {
  198145: {
    ClothesInteriorID: 198145,
    ClothesID: 1,
    Suggestions: {
      1: {
        male: [
          { componentID: 3, drawableID: 1, textureID: 0 },
          { componentID: 4, drawableID: 10, textureID: 0 },
          { componentID: 6, drawableID: 97, textureID: 0 },
          { componentID: 8, drawableID: 3, textureID: 0 },
          { componentID: 11, drawableID: 4, textureID: 0 },
        ],
        female: [],
      },
    },
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [
        {
          ComponentID: 4,
          ComponentName: "Legs",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 0,
            },
            {
              nameInInvoice: "Shalvar jin",
              DrawableID: 2,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "Shalvar jin2",
              DrawableID: 10,
              isNeedTorsos: false,
              Price: 1,
            },
          ],
        },
      ],
      female: [],
    },
    ClothProp: {
      male: [
        {
          PropID: 0,
          PropName: "Hats",
          Drawables: [
            {
              nameInInvoice: "Nothing",
              DrawableID: 8,
              isNeedTorsos: false,
              Price: 0,
            },
            {
              nameInInvoice: "test1",
              DrawableID: 0,
              isNeedTorsos: false,
              Price: 1,
            },
            {
              nameInInvoice: "test1",
              DrawableID: 2,
              isNeedTorsos: false,
              Price: 1,
            },
          ],
        },
      ],
      female: [],
    },
  },
  171265: {
    ClothesInteriorID: 171265,
    ClothesID: 2,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  169217: {
    ClothesInteriorID: 169217,
    ClothesID: 3,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  137217: {
    ClothesInteriorID: 137217,
    ClothesID: 4,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  166145: {
    ClothesInteriorID: 166145,
    ClothesID: 5,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  165633: {
    ClothesInteriorID: 165633,
    ClothesID: 6,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  235265: {
    ClothesInteriorID: 235265,
    ClothesID: 7,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  140801: {
    ClothesInteriorID: 140801,
    ClothesID: 8,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  176129: {
    ClothesInteriorID: 176129,
    ClothesID: 9,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  175361: {
    ClothesInteriorID: 175361,
    ClothesID: 10,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  202497: {
    ClothesInteriorID: 202497,
    ClothesID: 11,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  183553: {
    ClothesInteriorID: 183553,
    ClothesID: 12,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
  179713: {
    ClothesInteriorID: 179713,
    ClothesID: 13,
    Suggestions: {},
    ClothDLC: {},
    ClothComponent: {
      default: {
        male: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
        female: [
          { ComponentID: 1, DrawableID: 0, textureID: 0 },
          { ComponentID: 2, DrawableID: 0, textureID: 0 },
          { ComponentID: 4, DrawableID: 0, textureID: 0 },
          { ComponentID: 5, DrawableID: 0, textureID: 0 },
          { ComponentID: 6, DrawableID: 0, textureID: 0 },
          { ComponentID: 7, DrawableID: 0, textureID: 0 },
          { ComponentID: 8, DrawableID: 0, textureID: 0 },
          { ComponentID: 9, DrawableID: 0, textureID: 0 },
          { ComponentID: 10, DrawableID: 0, textureID: 0 },
          { ComponentID: 11, DrawableID: 0, textureID: 0 },
        ],
      },
      male: [],
      female: [],
    },
    ClothProp: {
      male: [],
      female: [],
    },
  },
};
