export let WebViewStatus = {
  musicVue: {
    name: "musicVue",
    priority: 110,
    isActive: false,
    isOpen: false,
    isMultiView: true,
    isNeedGameControl: false,
    EventNames: {
      ready: "WEBclient:MusicVue:mountedAndReady",
    },
  },
  loadingPage: {
    name: "loadingPage",
    priority: 100,
    isActive: false,
    isOpen: false,
    isMultiView: false,
    isNeedGameControl: false,
    EventNames: {
      ready: "ClientWEB:LoadingPageWebView:Ready",
      fullLoad: "ClientWEB:LoadingPageWebView:FullLoaded",
      ProcessText: "ClientWEB:LoadingPageWebView:ProcessText",
      destroy: "ClientWEB:LoadingPageWebView:Destroy",
    },
  },
  login: {
    name: "login",
    priority: 95,
    isActive: false,
    isOpen: false,
    isMultiView: false,
    isNeedGameControl: true,
    EventNames: {
      load: "ClientWEB:LoginWebView:Load",
      unLoad: "ClientWEB:LoginWebView:unLoad",
      close: "ClientWEB:LoginWebView:close",
    },
  },
  scoreBoard: {
    name: "scoreBoard",
    priority: 90,
    isActive: false,
    isOpen: false,
    isMultiView: false,
    isNeedGameControl: false,
    EventNames: {
      load: "ClientWEB:scoreBoardWebView:Load",
      unLoad: "ClientWEB:scoreBoardWebView:unLoad",
      close: "ClientWEB:scoreBoardWebView:close",
    },
  },
  chat: {
    name: "chat",
    priority: 89,
    isActive: false,
    isOpen: false,
    isMultiView: true,
    isNeedGameControl: false,
    EventNames: {
      load: "ClientWEB:ChatWebView:Load",
      unLoad: "ClientWEB:ChatWebView:unLoad",
      close: "ClientWEB:ChatWebView:close",
    },
  },
  phone: {
    name: "phone",
    priority: 88,
    isActive: false,
    isOpen: false,
    isMultiView: true,
    isNeedGameControl: false,
    EventNames: {
      ready: "ClientWEB:PhoneWebView:Ready",
      load: "ClientWEB:PhoneWebView:Load",
      unLoad: "ClientWEB:PhoneWebView:unLoad",
      close: "ClientWEB:PhoneWebView:close",
    },
  },
  speedOmeter: {
    name: "speedOmeter",
    priority: 87,
    isActive: false,
    isOpen: false,
    isMultiView: true,
    isNeedGameControl: false,
    EventNames: {
      load: "ClientWEB:SpeedOmeterWebView:Load",
      unLoad: "ClientWEB:SpeedOmeterWebView:unLoad",
      close: "ClientWEB:SpeedOmeterWebView:close",
    },
  },
  clothes: {
    name: "clothes",
    priority: 87,
    isActive: false,
    isOpen: false,
    isMultiView: false,
    isNeedGameControl: true,
    EventNames: {
      load: "ClientWEB:ClothesWebView:Load",
      unLoad: "ClientWEB:ClothesWebView:unLoad",
      close: "ClientWEB:ClothesWebView:close",
    },
  },
  eyeTracker: {
    name: "eyeTracker",
    priority: 10,
    isActive: false,
    isOpen: false,
    isMultiView: true,
    isNeedGameControl: false,
    EventNames: {
      load: "ClientWEB:eyeTrackerWebView:Load",
      unLoad: "ClientWEB:eyeTrackerWebView:unLoad",
      close: "ClientWEB:eyeTrackerWebView:close",
    },
  },
  IntroVue: {
    EventNames: {
      load: "ClientWEB:IntroMusic:Load",
      unLoad: "ClientWEB:IntroMusic:unLoad",
    },
  },
};
